name: flutter_libserialport_example
description: Demonstrates how to use the flutter_libserialport plugin.
publish_to: 'none'

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport:
    path: ../

flutter:
  uses-material-design: true